"use client";

import { useState } from "react";
import Link from "next/link";
import {
  Wand2,
  Music,
  Video,
  Mic,
  Headphones,
  Globe,
  ArrowRight,
  Check,
  ChevronDown,
  Menu,
  X,
  Star,
  MessageCircle,
  Share2,
  Mail,
  Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Logo } from "@/components/shared/Logo";

// ---------------------------------------------------------------------------
// Data
// ---------------------------------------------------------------------------

const FEATURES = [
  {
    icon: Wand2,
    title: "AI Course Builder",
    description:
      "Describe your topic and Claude AI scaffolds a complete, structured course — outlines, lessons, scripts, and assessments — in seconds.",
  },
  {
    icon: Music,
    title: "Lyric Studio",
    description:
      "Turn chord progressions and melodies into full lyric drafts. Perfect for music educators teaching songwriting.",
  },
  {
    icon: Video,
    title: "VSL Creator",
    description:
      "Auto-generate polished Video Sales Letters with on-brand animations, narration, and on-screen text from a single brief.",
  },
  {
    icon: Mic,
    title: "Voice Generation",
    description:
      "ElevenLabs voices bring your scripts to life — choose from 30+ professional voices or clone your own.",
  },
  {
    icon: Headphones,
    title: "Music Library",
    description:
      "Browse and embed royalty-free background music directly into lessons, intros, and sales videos.",
  },
  {
    icon: Globe,
    title: "One-Click Publish",
    description:
      "Deploy course portals and sales pages to a hosted URL in one click. Custom domains included on Pro+.",
  },
];

const PLANS = [
  {
    id: "starter",
    name: "Starter",
    price: 49,
    features: [
      "3 projects",
      "10 video renders/month",
      "50 AI generations/month",
      "5 GB storage",
      "1 team member",
      "Course portal",
      "Email support",
    ],
    popular: false,
    cta: "Get started free",
  },
  {
    id: "pro",
    name: "Pro",
    price: 149,
    features: [
      "25 projects",
      "100 video renders/month",
      "500 AI generations/month",
      "50 GB storage",
      "5 team members",
      "VSL builder",
      "Custom domain",
      "Priority support",
    ],
    popular: true,
    cta: "Start Pro free",
  },
  {
    id: "agency",
    name: "Agency",
    price: 399,
    features: [
      "Unlimited projects",
      "500 video renders/month",
      "2,000 AI generations/month",
      "200 GB storage",
      "25 team members",
      "White-label",
      "Client portals",
      "Dedicated support",
    ],
    popular: false,
    cta: "Contact us",
  },
];

const FAQS = [
  {
    q: "Do I need any video editing experience?",
    a: "Not at all. Soniq handles the entire production pipeline — script, voice, animation, and rendering — automatically. If you can describe what you want to teach, you can publish a course.",
  },
  {
    q: "Which AI models power the platform?",
    a: "Course scripts and copy are generated by Claude (Anthropic). Voiceover is powered by ElevenLabs. Video rendering uses Remotion. You get the best-in-class AI stack under one roof.",
  },
  {
    q: "Can I use my own voice?",
    a: "Yes — Pro and Agency plans support voice cloning via ElevenLabs. Upload a 30-second sample and all future voiceovers are rendered in your voice.",
  },
  {
    q: "What formats can I export my courses in?",
    a: "You can export as MP4 video, PDF workbook, PPTX slides, SCORM package, or a full ZIP bundle. Everything is also hosted on a course portal you can share immediately.",
  },
  {
    q: "Is there a free trial?",
    a: "Every plan starts with a 7-day free trial — no credit card required. You get access to all features on your chosen tier so you can see real results before you pay.",
  },
  {
    q: "Can I white-label the student portal?",
    a: "White-labeling — including custom domain, logo, and color scheme — is available on the Agency plan. Your students see your brand, not ours.",
  },
];

const STEPS = [
  {
    num: "01",
    title: "Describe your course",
    body: "Enter your topic, target audience, and a few key ideas. Add reference materials or let the AI start from scratch.",
  },
  {
    num: "02",
    title: "AI generates everything",
    body: "Soniq writes the scripts, renders the videos, synthesizes the voiceover, and assembles the course portal automatically.",
  },
  {
    num: "03",
    title: "Publish and sell",
    body: "Hit publish to get a live URL. Connect Stripe to start selling within minutes — no extra tools needed.",
  },
];

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function FaqItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-zinc-800 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between px-6 py-5 text-left gap-4 hover:bg-zinc-900 transition-colors"
        aria-expanded={open}
      >
        <span className="font-medium text-zinc-100">{q}</span>
        <ChevronDown
          className={`h-5 w-5 text-zinc-400 shrink-0 transition-transform duration-200 ${open ? "rotate-180" : ""}`}
        />
      </button>
      {open && (
        <div className="px-6 pb-5 text-zinc-400 text-sm leading-relaxed border-t border-zinc-800">
          <p className="pt-4">{a}</p>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function MarketingPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100">
      {/* ------------------------------------------------------------------ */}
      {/* NAV */}
      {/* ------------------------------------------------------------------ */}
      <header className="sticky top-0 z-50 border-b border-zinc-800/60 bg-zinc-950/80 backdrop-blur-md">
        <div className="container mx-auto flex h-16 items-center justify-between px-4 sm:px-6">
          <Logo />

          {/* Desktop nav */}
          <nav className="hidden md:flex items-center gap-8 text-sm text-zinc-400">
            <a href="#features" className="hover:text-zinc-100 transition-colors">
              Features
            </a>
            <a href="#how-it-works" className="hover:text-zinc-100 transition-colors">
              How it works
            </a>
            <a href="#pricing" className="hover:text-zinc-100 transition-colors">
              Pricing
            </a>
            <a href="#faq" className="hover:text-zinc-100 transition-colors">
              FAQ
            </a>
          </nav>

          <div className="hidden md:flex items-center gap-3">
            <Link href="/login">
              <Button variant="ghost" size="sm" className="text-zinc-300 hover:text-zinc-100 hover:bg-zinc-800">
                Log in
              </Button>
            </Link>
            <Link href="/signup">
              <Button size="sm" className="bg-violet-600 hover:bg-violet-500 text-white">
                Get Started
              </Button>
            </Link>
          </div>

          {/* Mobile hamburger */}
          <button
            className="md:hidden p-2 rounded-md text-zinc-400 hover:text-zinc-100 hover:bg-zinc-800 transition-colors"
            onClick={() => setMobileMenuOpen((v) => !v)}
            aria-label="Toggle menu"
          >
            {mobileMenuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
          </button>
        </div>

        {/* Mobile menu */}
        {mobileMenuOpen && (
          <div className="md:hidden border-t border-zinc-800 bg-zinc-950 px-4 py-4 space-y-4">
            <nav className="flex flex-col gap-3 text-sm text-zinc-400">
              {["#features", "#how-it-works", "#pricing", "#faq"].map((href) => (
                <a
                  key={href}
                  href={href}
                  className="hover:text-zinc-100 capitalize transition-colors"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  {href.replace("#", "").replace(/-/g, " ")}
                </a>
              ))}
            </nav>
            <div className="flex flex-col gap-2 pt-2 border-t border-zinc-800">
              <Link href="/login" onClick={() => setMobileMenuOpen(false)}>
                <Button variant="outline" className="w-full border-zinc-700 text-zinc-300 hover:bg-zinc-800 hover:text-zinc-100">
                  Log in
                </Button>
              </Link>
              <Link href="/signup" onClick={() => setMobileMenuOpen(false)}>
                <Button className="w-full bg-violet-600 hover:bg-violet-500 text-white">
                  Get Started
                </Button>
              </Link>
            </div>
          </div>
        )}
      </header>

      {/* ------------------------------------------------------------------ */}
      {/* HERO */}
      {/* ------------------------------------------------------------------ */}
      <section className="relative overflow-hidden">
        {/* Background gradient */}
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_80%_60%_at_50%_-10%,rgba(124,58,237,0.3),transparent)]"
        />
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_40%_30%_at_70%_80%,rgba(124,58,237,0.12),transparent)]"
        />

        <div className="container relative mx-auto px-4 sm:px-6 pt-20 pb-24 text-center">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 rounded-full border border-violet-500/30 bg-violet-500/10 px-4 py-1.5 text-sm text-violet-300 mb-8">
            <Zap className="h-3.5 w-3.5" />
            Powered by Claude AI + ElevenLabs
          </div>

          {/* Headline */}
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight max-w-4xl mx-auto leading-tight mb-6">
            AI-Powered Course Creation{" "}
            <span className="bg-gradient-to-r from-violet-400 to-violet-600 bg-clip-text text-transparent">
              for Music Educators
            </span>
          </h1>

          <p className="text-lg sm:text-xl text-zinc-400 max-w-2xl mx-auto mb-10 leading-relaxed">
            Describe your course, let Soniq generate the scripts, voiceover,
            videos, and sales page — then publish and sell in minutes.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
            <Link href="/signup">
              <Button size="lg" className="bg-violet-600 hover:bg-violet-500 text-white px-8 h-12 text-base">
                Start Free
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
            <a href="#features">
              <Button
                size="lg"
                variant="outline"
                className="border-zinc-700 text-zinc-300 hover:bg-zinc-800 hover:text-zinc-100 h-12 text-base"
              >
                See Demo
              </Button>
            </a>
          </div>

          {/* Mock UI screenshot */}
          <div className="relative mx-auto max-w-4xl rounded-2xl border border-zinc-700/60 bg-zinc-900 shadow-2xl shadow-violet-950/30 overflow-hidden">
            {/* Fake window chrome */}
            <div className="flex items-center gap-2 px-4 py-3 border-b border-zinc-800 bg-zinc-900/80">
              <span className="h-3 w-3 rounded-full bg-red-500/70" />
              <span className="h-3 w-3 rounded-full bg-yellow-500/70" />
              <span className="h-3 w-3 rounded-full bg-green-500/70" />
              <div className="flex-1 mx-4">
                <div className="h-5 rounded-md bg-zinc-800 max-w-xs mx-auto" />
              </div>
            </div>

            {/* Fake editor UI */}
            <div className="flex">
              {/* Sidebar */}
              <div className="hidden sm:flex flex-col w-52 border-r border-zinc-800 p-4 gap-2">
                <div className="h-3 rounded bg-violet-600/70 w-full mb-3" />
                {["Module 1 — Intro", "Module 2 — Scales", "Module 3 — Chords", "Module 4 — Melody"].map((m, i) => (
                  <div
                    key={m}
                    className={`h-8 rounded-lg flex items-center px-3 text-xs ${i === 1 ? "bg-violet-600/20 border border-violet-600/40 text-violet-300" : "bg-zinc-800/60 text-zinc-500"}`}
                  >
                    {m}
                  </div>
                ))}
                <div className="mt-4 space-y-2">
                  <div className="h-2 rounded bg-zinc-800 w-3/4" />
                  <div className="h-2 rounded bg-zinc-800 w-1/2" />
                  <div className="h-2 rounded bg-zinc-800 w-5/6" />
                </div>
              </div>

              {/* Main content */}
              <div className="flex-1 p-6 space-y-4">
                <div className="flex items-center justify-between">
                  <div className="h-6 rounded bg-zinc-700 w-48" />
                  <div className="h-7 rounded-lg bg-violet-600/80 w-24 text-xs flex items-center justify-center text-violet-100 text-[11px] font-medium">
                    AI Generate
                  </div>
                </div>

                {/* Script area */}
                <div className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-4 space-y-2">
                  <div className="h-2.5 rounded bg-zinc-700 w-full" />
                  <div className="h-2.5 rounded bg-zinc-700 w-5/6" />
                  <div className="h-2.5 rounded bg-zinc-700 w-4/5" />
                  <div className="h-2.5 rounded bg-zinc-800 w-2/3 mt-3" />
                  <div className="h-2.5 rounded bg-zinc-800 w-full" />
                  <div className="h-2.5 rounded bg-zinc-800 w-3/4" />
                </div>

                {/* Voiceover bar */}
                <div className="rounded-xl border border-zinc-800 bg-zinc-900/80 p-3 flex items-center gap-3">
                  <div className="h-8 w-8 rounded-full bg-violet-600/30 flex items-center justify-center shrink-0">
                    <Mic className="h-3.5 w-3.5 text-violet-400" />
                  </div>
                  <div className="flex-1 space-y-1">
                    <div className="h-2 rounded-full bg-zinc-700 w-full overflow-hidden">
                      <div className="h-full w-2/3 rounded-full bg-gradient-to-r from-violet-600 to-violet-400" />
                    </div>
                    <div className="h-1.5 rounded bg-zinc-800 w-20" />
                  </div>
                  <div className="h-7 w-16 rounded-lg bg-emerald-600/70 text-[11px] flex items-center justify-center text-emerald-100 font-medium shrink-0">
                    Render
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ------------------------------------------------------------------ */}
      {/* SOCIAL PROOF BAR */}
      {/* ------------------------------------------------------------------ */}
      <div className="border-y border-zinc-800 bg-zinc-900/50">
        <div className="container mx-auto px-4 sm:px-6 py-6 flex flex-col sm:flex-row items-center justify-center gap-6 sm:gap-12 text-sm text-zinc-400">
          <div className="flex items-center gap-2">
            <div className="flex">
              {[...Array(5)].map((_, i) => (
                <Star key={i} className="h-4 w-4 text-amber-400 fill-amber-400" />
              ))}
            </div>
            <span>
              <strong className="text-zinc-100">4.9/5</strong> from 300+ reviews
            </span>
          </div>
          <div className="hidden sm:block h-4 w-px bg-zinc-700" />
          <span>
            Trusted by{" "}
            <strong className="text-zinc-100">1,000+ creators</strong> worldwide
          </span>
          <div className="hidden sm:block h-4 w-px bg-zinc-700" />
          <div className="flex items-center gap-2">
            <Zap className="h-4 w-4 text-violet-400" />
            <span>
              <strong className="text-zinc-100">50,000+</strong> courses published
            </span>
          </div>
        </div>
      </div>

      {/* ------------------------------------------------------------------ */}
      {/* FEATURES */}
      {/* ------------------------------------------------------------------ */}
      <section id="features" className="container mx-auto px-4 sm:px-6 py-24 scroll-mt-16">
        <div className="text-center mb-16">
          <p className="text-sm font-semibold text-violet-400 uppercase tracking-widest mb-3">
            Features
          </p>
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
            Everything you need to create and sell
          </h2>
          <p className="text-zinc-400 max-w-xl mx-auto">
            One platform replaces your video editor, voiceover studio, course
            builder, and landing page tool.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {FEATURES.map((f) => {
            const Icon = f.icon;
            return (
              <div
                key={f.title}
                className="group rounded-2xl border border-zinc-800 bg-zinc-900/60 p-6 hover:border-violet-600/50 hover:bg-zinc-900 transition-all duration-200"
              >
                <div className="mb-4 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-violet-600/15 border border-violet-600/20 group-hover:bg-violet-600/25 transition-colors">
                  <Icon className="h-5 w-5 text-violet-400" />
                </div>
                <h3 className="font-semibold text-zinc-100 mb-2">{f.title}</h3>
                <p className="text-sm text-zinc-400 leading-relaxed">{f.description}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* ------------------------------------------------------------------ */}
      {/* HOW IT WORKS */}
      {/* ------------------------------------------------------------------ */}
      <section id="how-it-works" className="bg-zinc-900/40 border-y border-zinc-800 scroll-mt-16">
        <div className="container mx-auto px-4 sm:px-6 py-24">
          <div className="text-center mb-16">
            <p className="text-sm font-semibold text-violet-400 uppercase tracking-widest mb-3">
              How it works
            </p>
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight">
              From idea to live course in 3 steps
            </h2>
          </div>

          <div className="relative grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            {/* Connector line — desktop only */}
            <div
              aria-hidden
              className="hidden md:block absolute top-10 left-1/3 right-1/3 h-px bg-gradient-to-r from-violet-600/0 via-violet-600/50 to-violet-600/0"
            />

            {STEPS.map((step) => (
              <div key={step.num} className="flex flex-col items-center text-center">
                <div className="mb-5 flex h-20 w-20 items-center justify-center rounded-2xl border border-violet-600/30 bg-violet-600/10 text-3xl font-bold text-violet-400">
                  {step.num}
                </div>
                <h3 className="font-semibold text-lg text-zinc-100 mb-2">{step.title}</h3>
                <p className="text-sm text-zinc-400 leading-relaxed">{step.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ------------------------------------------------------------------ */}
      {/* PRICING */}
      {/* ------------------------------------------------------------------ */}
      <section id="pricing" className="container mx-auto px-4 sm:px-6 py-24 scroll-mt-16">
        <div className="text-center mb-16">
          <p className="text-sm font-semibold text-violet-400 uppercase tracking-widest mb-3">
            Pricing
          </p>
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
            Simple, transparent pricing
          </h2>
          <p className="text-zinc-400 max-w-md mx-auto">
            Start free for 7 days. No credit card required. Cancel any time.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {PLANS.map((plan) => (
            <div
              key={plan.id}
              className={`relative flex flex-col rounded-2xl border p-8 ${
                plan.popular
                  ? "border-violet-600 bg-violet-600/5 shadow-lg shadow-violet-950/40"
                  : "border-zinc-800 bg-zinc-900/60"
              }`}
            >
              {plan.popular && (
                <div className="absolute -top-3.5 left-1/2 -translate-x-1/2">
                  <span className="inline-block rounded-full bg-violet-600 px-4 py-1 text-xs font-bold text-white uppercase tracking-wider">
                    Most Popular
                  </span>
                </div>
              )}

              <div className="mb-2 text-sm font-medium text-zinc-400 uppercase tracking-widest">
                {plan.name}
              </div>
              <div className="mb-6 flex items-end gap-1">
                <span className="text-4xl font-bold text-zinc-100">${plan.price}</span>
                <span className="text-zinc-500 mb-1">/month</span>
              </div>

              <ul className="mb-8 flex-1 space-y-3">
                {plan.features.map((f) => (
                  <li key={f} className="flex items-start gap-3 text-sm text-zinc-300">
                    <Check className="h-4 w-4 text-emerald-400 shrink-0 mt-0.5" />
                    {f}
                  </li>
                ))}
              </ul>

              <Link href="/signup">
                <Button
                  className={`w-full h-11 font-semibold ${
                    plan.popular
                      ? "bg-violet-600 hover:bg-violet-500 text-white"
                      : "border border-zinc-700 bg-transparent text-zinc-200 hover:bg-zinc-800 hover:text-zinc-100"
                  }`}
                >
                  {plan.cta}
                </Button>
              </Link>
            </div>
          ))}
        </div>
      </section>

      {/* ------------------------------------------------------------------ */}
      {/* FAQ */}
      {/* ------------------------------------------------------------------ */}
      <section id="faq" className="bg-zinc-900/40 border-t border-zinc-800 scroll-mt-16">
        <div className="container mx-auto px-4 sm:px-6 py-24">
          <div className="text-center mb-16">
            <p className="text-sm font-semibold text-violet-400 uppercase tracking-widest mb-3">
              FAQ
            </p>
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
              Frequently asked questions
            </h2>
            <p className="text-zinc-400 max-w-md mx-auto">
              Still have questions?{" "}
              <a href="mailto:hello@soniq.app" className="text-violet-400 hover:underline">
                Reach out to us
              </a>
              .
            </p>
          </div>

          <div className="max-w-2xl mx-auto space-y-3">
            {FAQS.map((item) => (
              <FaqItem key={item.q} q={item.q} a={item.a} />
            ))}
          </div>
        </div>
      </section>

      {/* ------------------------------------------------------------------ */}
      {/* CTA BANNER */}
      {/* ------------------------------------------------------------------ */}
      <section className="border-t border-zinc-800 bg-zinc-950">
        <div className="container mx-auto px-4 sm:px-6 py-24 text-center">
          <div
            aria-hidden
            className="pointer-events-none absolute inset-x-0 h-64 bg-[radial-gradient(ellipse_60%_40%_at_50%_50%,rgba(124,58,237,0.15),transparent)]"
          />
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
            Ready to publish your first course?
          </h2>
          <p className="text-zinc-400 mb-8 max-w-md mx-auto">
            Join 1,000+ creators building smarter with AI. First 7 days free.
          </p>
          <Link href="/signup">
            <Button size="lg" className="bg-violet-600 hover:bg-violet-500 text-white px-10 h-12 text-base">
              Start Building Free
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </Link>
        </div>
      </section>

      {/* ------------------------------------------------------------------ */}
      {/* FOOTER */}
      {/* ------------------------------------------------------------------ */}
      <footer className="border-t border-zinc-800 bg-zinc-950">
        <div className="container mx-auto px-4 sm:px-6 py-12">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
            {/* Brand */}
            <div className="space-y-4">
              <Logo />
              <p className="text-sm text-zinc-500 leading-relaxed max-w-xs">
                AI-powered course creation for music educators and online creators.
              </p>
              <div className="flex items-center gap-3">
                <a
                  href="https://twitter.com/soniqapp"
                  aria-label="Twitter / X"
                  className="text-zinc-500 hover:text-zinc-300 transition-colors"
                >
                  <MessageCircle className="h-5 w-5" />
                </a>
                <a
                  href="https://github.com/soniqapp"
                  aria-label="GitHub"
                  className="text-zinc-500 hover:text-zinc-300 transition-colors"
                >
                  <Share2 className="h-5 w-5" />
                </a>
                <a
                  href="mailto:hello@soniq.app"
                  aria-label="Email"
                  className="text-zinc-500 hover:text-zinc-300 transition-colors"
                >
                  <Mail className="h-5 w-5" />
                </a>
              </div>
            </div>

            {/* Product */}
            <div>
              <h4 className="text-sm font-semibold text-zinc-300 mb-4">Product</h4>
              <ul className="space-y-2 text-sm text-zinc-500">
                {[
                  ["Features", "#features"],
                  ["Pricing", "#pricing"],
                  ["Changelog", "/changelog"],
                  ["Roadmap", "/roadmap"],
                ].map(([label, href]) => (
                  <li key={label}>
                    <a href={href} className="hover:text-zinc-300 transition-colors">
                      {label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>

            {/* Resources */}
            <div>
              <h4 className="text-sm font-semibold text-zinc-300 mb-4">Resources</h4>
              <ul className="space-y-2 text-sm text-zinc-500">
                {[
                  ["Documentation", "/docs"],
                  ["Blog", "/blog"],
                  ["Templates", "/templates"],
                  ["Status", "/status"],
                ].map(([label, href]) => (
                  <li key={label}>
                    <a href={href} className="hover:text-zinc-300 transition-colors">
                      {label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>

            {/* Company */}
            <div>
              <h4 className="text-sm font-semibold text-zinc-300 mb-4">Company</h4>
              <ul className="space-y-2 text-sm text-zinc-500">
                {[
                  ["About", "/about"],
                  ["Careers", "/careers"],
                  ["Privacy", "/privacy"],
                  ["Terms", "/terms"],
                ].map(([label, href]) => (
                  <li key={label}>
                    <a href={href} className="hover:text-zinc-300 transition-colors">
                      {label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="border-t border-zinc-800 pt-6 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-zinc-600">
            <span>© {new Date().getFullYear()} Soniq. All rights reserved.</span>
            <span>
              Built with Claude AI +{" "}
              <span className="text-violet-500">ElevenLabs</span>
            </span>
          </div>
        </div>
      </footer>
    </div>
  );
}
